### ISSUE TITLE
UI - Footer

### ISSUE THREAD

**Issue by ToniDev182** [ToniDev182/BlackMesaCollective#6]

**Comment by SonRome** [comment]
Contacto
_fatfreemanblackmesa@gmail.com_

Logo Instagram - Linked to the instagram page of the colective
Future Logos (TBD)

Bottom
All rights reserved (Left)
Logo of the colective (Right)

**Comment by ToniDev182** [comment]
# Explicación Completa del Footer — Código y Estilos

## 1. Estructura del Footer en React
El footer se divide en **3 bloques principales** dentro de un contenedor flex:

- **Bloque izquierdo**: Logo y texto de derechos reservados.
- **Bloque central**: Texto descriptivo o lema.
- **Bloque derecho**: Iconos con enlaces (Instagram y contacto).

### Código JSX
```jsx
<div className="relative z-30 h-full w-full px-6 flex flex-col md:flex-row justify-between items-center gap-6">
  {/* Izquierda */}
  <div className="flex items-center gap-3">
    <img src="logo.png" alt="Logo" className="h-10 w-auto" />
    <p className="text-sm md:text-base">All rights reserved ©</p>
  </div>

  {/* Centro */}
  <div className="text-center max-w-3xl px-4">
    <h1 className="footer-center-text">
      Unidos por la música electrónica. Deep techno, house, breaks y drum and bass — pura energía y pasión underground.
    </h1>
  </div>

  {/* Derecha */}
  <div className="flex items-center gap-6">
    {/* Instagram */}
    <a href="https://instagram.com" className="flex flex-col items-center hover:scale-110 transition">
      <Instagram size={36} />
      <span className="text-xs mt-1">Instagram</span>
    </a>
    {/* Contacto */}
    <a href="mailto:email@example.com" className="flex flex-col items-center hover:scale-110 transition">
      <img src="logoC.png" alt="Contact" className="h-12 w-auto" />
      <span className="text-xs mt-1">Contáctanos</span>
    </a>
  </div>
</div>
```

### ¿Por qué usar `flex-col md:flex-row`?
- **Pantallas grandes (md en adelante)**: Los bloques se muestran en línea horizontal (fila).
- **Pantallas pequeñas**: Se apilan verticalmente para evitar solapamientos, manteniendo la legibilidad.

## 2. Fondo, Video y Capa de Mezcla
- **Video de fondo**: Con `z-index: 0` y `object-cover` para cubrir toda el área.
- **Imagen de fondo semitransparente**: Opacidad para darle textura y profundidad.
- **Capa roja**: Usa `mix-blend-multiply` para crear un filtro de color que genera un ambiente underground.

### Código JSX
```jsx
<video
  autoPlay
  loop
  muted
  playsInline
  preload="auto"
  className="absolute top-0 left-0 w-full h-full object-cover z-0"
>
  <source src={clip} type="video/mp4" />
  Tu navegador no soporta el video.
</video>

<div className="footer-background-image" /> {/* imagen con opacidad */}

<div className="absolute top-0 left-0 w-full h-full bg-red-600 mix-blend-multiply opacity-100 z-10" />
```

## 3. CSS Explicativo con Responsividad
### Código CSS
```css
.footer-background-image {
  background-image: url('https://i.postimg.cc/SxgXM9M9/footer-Mesa.png');
  background-position: center bottom;
  background-repeat: no-repeat;
  background-size: cover;
  
  /* Opacidad para no tapar mucho el video y contenido */
  opacity: 0.5;
  
  /* Posición absoluta para cubrir el footer */
  position: absolute;
  top: 0; 
  left: 0;
  width: 100%; 
  height: 100%;
  
  /* Se sitúa sobre el video (z-0) pero debajo del contenido */
  z-index: 5;
}

/* Texto centrado */
.footer-center-text {
  font-size: 1.125rem; /* Tamaño base para escritorio (aprox 18px) */
  max-width: 48rem;    /* Máximo ancho para evitar que el texto se extienda demasiado */
  font-weight: 600;    /* Negrita para resaltar */
  
  /* Sombra para mejorar legibilidad sobre el fondo */
  text-shadow: 0 1px 3px rgba(0,0,0,0.5);
}

/* Ajustes responsivos para tablets y móviles */
@media (max-width: 1024px) {
  .footer-center-text {
    font-size: 1rem;    /* Reducimos un poco el tamaño para tablets */
    max-width: 36rem;   /* También reducimos el ancho máximo */
  }

  /* Cambiar layout a columna para evitar solapamientos */
  footer > div.relative.z-30 {
    flex-direction: column;   /* De fila a columna */
    justify-content: center;
    gap: 1rem;                /* Espacio entre bloques */
    padding-bottom: 2rem;     /* Espacio extra abajo */
  }

  /* Centrar contenido en los bloques izquierdo y derecho */
  footer > div.relative.z-30 > div.flex.items-center.gap-3,
  footer > div.relative.z-30 > div.flex.items-center.gap-6 {
    justify-content: center;
    width: 100%;
  }
}

/* Ajustes adicionales para pantallas muy pequeñas (móviles) */
@media (max-width: 640px) {
  .footer-center-text {
    font-size: 0.875rem;  /* Más pequeño para móvil */
    max-width: 90%;       /* Se ajusta casi a todo el ancho */
  }

  /* Padding lateral para evitar que el contenido toque los bordes */
  footer > div.relative.z-30 {
    padding-left: 1rem;
    padding-right: 1rem;
  }
}
```

### Explicación Concreta
- **`.footer-background-image`**: La imagen de fondo se posiciona de forma absoluta, ocupa todo el contenedor y tiene una opacidad baja para no tapar el video. `z-index: 5` la sitúa entre el video (`z-0`) y el contenido (`z-30`).
- **`.footer-center-text`**: Controla el estilo del texto del centro, incluyendo tamaño, ancho máximo y sombra para mejorar la lectura sobre el fondo dinámico.
- **Media queries**:
  - A partir de 1024px y menos, el layout cambia a columna para evitar superposiciones.
  - Los bloques de texto y logos se centran y ocupan el ancho completo para mejor visualización en móvil/tablet.
  - El tamaño del texto central se reduce progresivamente para adaptarse a pantallas pequeñas.

## 4. Beneficios de esta Estructura
- **Claridad visual**: Los bloques están organizados y separados claramente.
- **Flexibilidad**: Flexbox permite cambiar dirección fácilmente (fila → columna).
- **Responsive**: El diseño se adapta para mantener legibilidad y evitar solapamientos.
- **Control de capas**: Uso correcto de `z-index` para superponer video, imagen, filtro y contenido.
- **Interacción suave**: Efecto `hover` con `scale` para iconos mejora la experiencia de usuario.

## Resumen Final
Este footer está construido para ofrecer:
- Un **video de fondo dinámico** que aporta movimiento y ambiente.
- Una **imagen estática semitransparente** que da textura y profundidad.
- Un **filtro rojo** con `mix-blend-multiply` para reforzar la estética underground.
- Un **texto central legible** y adaptado para cualquier pantalla.
- **Tres bloques** bien organizados que se acomodan horizontalmente en escritorio y verticalmente en dispositivos móviles.
- **Iconos con efectos visuales suaves** para mejorar la interacción.
